{
 "title": "ALEO | DOUBLETOP",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(blockheight_value{db=\"telegraf\"},owner)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(blockheight_value{owner=~\"$owner\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Высота блока",
   "type": "stat",
   "description": "Текущий блок на ноде",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blockheight_value{owner=~\"$owner\",host=~\"$instance\",db=\"telegraf\"}"
    }
   ]
  },
  {
   "title": "Подключено нод",
   "type": "stat",
   "description": "Сколько подключено под для синхронизации",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "connections_value{owner=~\"$owner\",host=~\"$instance\",db=\"telegraf\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Намайнено блоков",
   "type": "stat",
   "description": "Счетчик сбрасывается после перезагрузки",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minedcounter_value{owner=~\"$owner\",host=~\"$instance\",db=\"telegraf\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minedcounter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Версия",
   "type": "stat",
   "description": "Текущая версия snarkOS",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "getversion_value{owner=~\"$owner\",host=~\"$instance\",db=\"telegraf\"}",
     "measurement": "getversion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Блоки",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "blockheight_value{owner=~\"$owner\",host=~\"$instance\",db=\"telegraf\"}",
     "legendFormat": "Синхронизация блоков"
    }
   ]
  },
  {
   "title": "Майнинг",
   "type": "graph",
   "description": "Сколько блоков произвел майнер с момента последней перезагрузки",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minedcounter_value{owner=~\"$owner\",host=~\"$instance\",db=\"telegraf\"}",
     "legendFormat": "Намайнилось блоков"
    }
   ]
  }
 ]
}